apiVersion: apps/v1
kind: Deployment
metadata:
  name: basic-tikv-0
  labels:
    app: tikv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tikv
  template:
    metadata:
      labels:
        app: tikv
    spec:
      containers:
      - name: basic-tikv-0
        image: pingcap/tikv:latest
        ports:
          - containerPort: 20160
        args:
          - "--pd=http://pd-service:2380"
          - "--addr=0.0.0.0:20160"
          - "--advertise-addr=basic-tikv-peer.tidb-cluster.svc.cluster.local:20160"

---
apiVersion: v1
kind: Service
metadata:
  name: tikv-service
spec:
  selector:
    app: tikv
  ports:
    - protocol: TCP
      port: 20160
      targetPort: 20160
